version: "3.5"
services:
  search_page_fe:
    build: .
    image: ghcr.io/potasticmaeve/search_page_fe:1.0.0
    container_name: search_page_fe
    ports:
      - "5173:80"
    # volumes:
    #   - "./default.conf:/etc/nginx/conf.d/default.conf"
